import { useMemo, useState, type FormEvent } from "react";
import { MinusCircle, PackageMinus, SlidersHorizontal } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

export default function Issue() {
  const [search, setSearch] = useState("");
  const [productId, setProductId] = useState("");
  const [mode, setMode] = useState<"issue" | "adjustment">("issue");
  const [quantity, setQuantity] = useState("1");
  const [note, setNote] = useState("");
  const productsInput = useMemo(() => ({ search, category: "all" as const, status: "all" as const }), [search]);
  const productsQuery = trpc.products.list.useQuery(productsInput);
  const utils = trpc.useUtils();
  const issueMutation = trpc.inventory.issue.useMutation({ onSuccess: async () => { toast.success("บันทึกการจ่ายสินค้าแล้ว"); setQuantity("1"); setNote(""); await Promise.all([productsQuery.refetch(), utils.inventory.summary.invalidate(), utils.inventory.movementSummary.invalidate(), utils.movements.list.invalidate()]); }, onError: (error) => toast.error(error.message) });
  const adjustMutation = trpc.inventory.adjust.useMutation({ onSuccess: async () => { toast.success("บันทึกการปรับยอดแล้ว"); setQuantity(""); await Promise.all([productsQuery.refetch(), utils.inventory.summary.invalidate(), utils.inventory.movementSummary.invalidate(), utils.movements.list.invalidate()]); }, onError: (error) => toast.error(error.message) });
  const selected = productsQuery.data?.find((product) => String(product.id) === productId);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!selected) return toast.error("กรุณาเลือกสินค้า"); const value = Number(quantity); if (mode === "issue") issueMutation.mutate({ productId: selected.id, quantity: value, note: note || undefined }); else adjustMutation.mutate({ productId: selected.id, targetQuantity: value, note }); };
  const busy = issueMutation.isPending || adjustMutation.isPending;
  return <div className="mx-auto max-w-3xl"><div className="mb-6"><p className="mb-2 text-sm font-semibold text-primary">คลังสินค้า</p><h1 className="text-2xl font-bold tracking-tight lg:text-3xl">จ่ายสินค้าออก / ปรับยอด</h1><p className="mt-1 text-sm text-muted-foreground">ทุกการเปลี่ยนแปลงจะถูกบันทึกในประวัติ stock movement</p></div><Card className="border-0 shadow-[var(--shadow-card)]"><CardHeader><div className="flex flex-wrap gap-2"><Button type="button" variant={mode === "issue" ? "default" : "outline"} className="gap-2" onClick={() => setMode("issue")}><PackageMinus className="size-4" />จ่ายสินค้าออก</Button><Button type="button" variant={mode === "adjustment" ? "default" : "outline"} className="gap-2" onClick={() => setMode("adjustment")}><SlidersHorizontal className="size-4" />ปรับยอดจากการนับจริง</Button></div><CardTitle className="pt-3 text-base">{mode === "issue" ? "บันทึกการจ่ายสินค้า" : "ปรับยอดคงเหลือ"}</CardTitle></CardHeader><CardContent><form className="space-y-5" onSubmit={submit}><div className="space-y-2"><label className="text-sm font-medium" htmlFor="issue-search">ค้นหาสินค้า</label><Input id="issue-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ชื่อสินค้า, SKU หรือ barcode" /></div><div className="space-y-2"><label className="text-sm font-medium" htmlFor="issue-product">สินค้า</label><select id="issue-product" className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={productId} onChange={(event) => setProductId(event.target.value)}><option value="">เลือกสินค้า</option>{productsQuery.data?.map((product) => <option key={product.id} value={product.id}>{product.name} · คงเหลือ {product.quantity} {product.unit}</option>)}</select></div>{selected ? <div className="rounded-xl bg-secondary/60 p-4 text-sm"><p className="font-semibold">{selected.name}</p><p className="mt-1 text-muted-foreground">คงเหลือปัจจุบัน {selected.quantity} {selected.unit} · SKU {selected.sku}</p></div> : null}<div className="space-y-2"><label className="text-sm font-medium" htmlFor="issue-quantity">{mode === "issue" ? `จำนวนที่จ่าย (${selected?.unit ?? "หน่วย"})` : `ยอดคงเหลือใหม่ (${selected?.unit ?? "หน่วย"})`}</label><Input id="issue-quantity" type="number" min={mode === "issue" ? "1" : "0"} value={quantity} onChange={(event) => setQuantity(event.target.value)} /></div><div className="space-y-2"><label className="text-sm font-medium" htmlFor="issue-note">หมายเหตุ {mode === "adjustment" ? "(จำเป็น)" : "(ถ้ามี)"}</label><Input id="issue-note" value={note} onChange={(event) => setNote(event.target.value)} placeholder={mode === "issue" ? "เช่น ขายหน้าร้าน / สินค้าเสียหาย" : "เช่น ตรวจนับสต็อกประจำสัปดาห์"} /></div><Button type="submit" disabled={busy || !selected} className="w-full gap-2"><MinusCircle className="size-4" />{busy ? "กำลังบันทึก…" : mode === "issue" ? "ยืนยันจ่ายสินค้าออก" : "บันทึกการปรับยอด"}</Button></form></CardContent></Card></div>;
}
